### ISSUE TITLE
using my own custom dataset

### ISSUE THREAD

**Issue by nikky4D** [mmaaz60/mvits_for_class_agnostic_od#8]
I would like to finetune on my own dataset. Do you have recommendations on how I can create my own dataset for this?

**Comment by nikky4D** [comment]
I have a question on the pretraining. I want to pretrain only on my dataset. Can i modify pretrain.json to only specify path to my dataset? what else should I change to get pretraining?

**Comment by mmaaz60** [comment]
> I have a question on the pretraining. I want to pretrain only on my dataset. Can i modify pretrain.json to only specify path to my dataset? what else should I change to get pretraining?

Hi @nikky4D,

Thank you for your interest in our work. We use the same setup as of [MDETR](https://github.com/ashkamath/mdetr/blob/main/.github/pretrain.md) for pretraining our model. Specifically, we trained on approximately 1.3 M image-caption pairs from GQA, COCO & Flicker.

In order to train on your custom dataset, you will need to convert your dataset in COCO format containing captions and `tokens_positive` defining alignment with the bounding boxes. The issue [at](https://github.com/ashkamath/mdetr/issues/51) explains the required format of `tokens_positive`. Further, the standard data loader used can be found [at](https://github.com/mmaaz60/mdef_detr/blob/71126c87983c519df47d7f99fb8c8d2e3531b7e2/datasets/coco.py#L18).

In addition to that, you can also evaluate MDef-DETR on your dataset without any pretraining/fine-tuning. Please refer to [this issue](https://github.com/mmaaz60/mvits_for_class_agnostic_od/issues/4) for details.

I hope this information will be helpful.
